version: "3.5"

services:
    frda:
        image: node:13-alpine
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - 4999:3000
        command: npm run start-api
    redoc:
        image: node:13-alpine
        volumes:
            - .:/app
        working_dir: "/app"
        user: "${UID}:${GID}"
        ports:
            - 5000:5000
        command: "npm run openapi:serve"
    swagger-ui:
        image: swaggerapi/swagger-ui
        volumes:
            - ./openapi:/openapi
        environment:
            - SWAGGER_JSON=/openapi/openapi.json
        ports:
            - 5001:8080
    swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
            - 5002:8080
    prism:
        image: stoplight/prism:3
        volumes:
            - ./openapi:/openapi
        ports:
            - 5003:4010
        command: mock -d -h 0.0.0.0 "/openapi/openapi.json"
    api-sprout:
        image: danielgtaylor/apisprout
        volumes:
            - ./openapi:/openapi
        ports:
            - 5004:8000
        command: --watch /openapi/openapi.json
